version: '3.4'

services:
  modelo.webapi:
    image: ${DOCKER_REGISTRY}modelowebapi
    build:
      context: .
      dockerfile: Modelo.WebApi/Dockerfile
    depends_on:
      - nosql.data

  nosql.data:
    image: mongo
    networks:
      static-network:
        ipv4_address: 172.20.128.2

  rabbitmq:
    image: rabbitmq:3-management-alpine